"""empty message

Revision ID: e54b707190db
Revises: 7b341695f43f
Create Date: 2022-10-13 18:56:58.511474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54b707190db'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=480), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=250), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'salt')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
